### ISSUE TITLE
links to the dataset features is broken

### ISSUE THREAD

**Issue by ZhenZHAO** [IsaacChanghau/SeqPAN#1]
Hi Hao,

Thanks for your great job. also your great survey.

I am new to TSGV, and I am trying to use your SeqPAN as my try for span-based method. (any suggestion is )

The provided Box Drive is broken, Can you please fix the link??

Bests,

Zhen

**Comment by 26hzhang** [comment]
Hi Zhao Zhen,Thanks for the notification. I’ll try to fix the issue once I’m available.Best regards,Zhang HaoOn 10 Jan 2023, at 20:02, Zhen ZHAO ***@***.***> wrote:﻿
Hi Hao,
Thanks for your great job. also your great survey.
I am new to TSGV, and I am trying to use your SeqPAN as my try for span-based method. (any suggestion is )
The provided Box Drive is broken, Can you please fix the link??
Bests,
Zhen
